### ISSUE TITLE
Deploy client gateway

### ISSUE THREAD

**Issue by nicolasbrugneaux** [celo-org/safe-client-gateway#23]
- [x] staging
- [x] production

**Comment by alvarof2** [comment]
Deployed in [staging](https://console.cloud.google.com/kubernetes/clusters/details/us-west1-a/celo-safe-staging/details?project=clabs-gnosis-safe&supportedpurview=project) and [prod](https://console.cloud.google.com/kubernetes/clusters/details/us-central1/celo-safe-prod/details?project=clabs-gnosis-safe&supportedpurview=project) for Alfajores and mainnet
